name: 🎉 Release Notify

on:
  release:
    # published: latest release 和 pre release 都会触发
    # prereleased: 只有 pre release 触发
    # released: 只有 latest release 触发
    types: [released]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Latest Release Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "🎉 AntV/S2 新版本发布啦 🎉",
                "text": "📋 点击查看更新日志",
                "messageUrl": "https://github.com/antvis/S2/releases",
                "picUrl": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*1PTTQLk3j5AAAAAAAAAAAAAADmJ7AQ/original"
              }
            }

      - name: Latest Release Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_GROUP_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "🎉 AntV/S2 新版本发布啦 🎉",
                "text": "📋 点击查看更新日志",
                "messageUrl": "https://github.com/antvis/S2/releases",
                "picUrl": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*1PTTQLk3j5AAAAAAAAAAAAAADmJ7AQ/original"
              }
            }

      - name: Latest Release Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_PUBLIC_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "🎉 AntV/S2 新版本发布啦 🎉",
                "text": "📋 点击查看更新日志",
                "messageUrl": "https://github.com/antvis/S2/releases",
                "picUrl": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*1PTTQLk3j5AAAAAAAAAAAAAADmJ7AQ/original"
              }
            }
